### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cfinn68916** [Brown-County-FIRST-Robotics/SecondSight#9]
- [x] Add endpoint for Apriltag positions
- [x] Add networktables API
- [x] Add endpoint for Apriltag field positions
- [ ] Finish camera streaming code
- [ ] Add preview to config UI
- [ ] Add USB auto complete to config UI
- [x] Add roles to config UI
- [x] Add pos to config UI
- [x] Add a redirect sinkhole when there is no config
- [x] Add calibration UI
